app/urls.py
from app.views import *
from django.urls import path

app_name='clientfirst'
urlpatterns=[
    path('client/',client,name='client'),
    
]

app1/urls.py
from app1.views import *
from django.urls import path

app_name='secondserver'

urlpatterns=[
    path('server/',server,name='server'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app,app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app1/',include('app1.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def client(request):
    return render(request,'client.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def server(request):
    return render(request,'server.html')

templates/client.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>I'm client and i need service</h1>
        <h2>Is it available</h2>
        <h2><a href="{% url 'secondserver:server' %}">Response</a></h2>
    </center>
</body>
</html>

templates/server.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hai iam server, how can i help you?</h1>
        <h2><a href="{% url 'clientfirst:client' %}">Return</a></h2>
    </center>
</body>
</html>